all: add_numbers

add_numbers: add_numbers.cpp
	g++ -o add_numbers add_numbers.cpp

dump: add_numbers.exe
	objdump -d add_numbers.exe > add_numbers.asm

clean:
	del add_numbers.asm

run: add_numbers.exe
	add_numbers.exe